### ISSUE TITLE
Modify Heatshrink Compression Parameters

### ISSUE THREAD

**Issue by laukik-hase** [eerimoq/detools#6]
Thank you for this amazing project! I ported it for ESP32 ([here](https://github.com/laukik-hase/esp32_compressed_delta_ota_update)) and it worked like a charm!

Is there a way to modify the Heatshrink compression parameters (window size, look ahead buffer) from the command-line? 
Something like - 
`detools create_patch -c heatshrink --wbit 8 --lookahead 7...`

**Comment by eerimoq** [comment]
Hi!

It's not possible today, but feel free to implement it and submit a PR and I'll have a look at it. Hopefully it's easy to implement.

Erik

**Comment by laukik-hase** [comment]
Ok, thanks for your response! I am closing this issue, as this is a feature request.

**Comment by eerimoq** [comment]
I implemented it. Part of version 0.49.0!
