### ISSUE TITLE
In-place patching: `memory-size` and `segment-size`

### ISSUE THREAD

**Issue by laukik-hase** [eerimoq/detools#9]
Hello, @eerimoq!

- Could you please explain the parameters `memory-size` and `segment-size` and their usage for the in-place patching mechanism?
- On what basis do I select these values while creating an in-place patch?
- Do I need to configure these values in any way while applying patches in the C implementation?
- Could you also explain the usage of `step_set` and `step_get` callbacks in the C implementation?

Thanks a lot!

**Comment by eerimoq** [comment]
Does this help: https://detools.readthedocs.io/en/latest/#id3
